name:                manifold-hedger
version:             0.1.0.0
github:              "githubuser/manifold-hedger"
license:             BSD3
author:              "Fabrizio Genovese, Philipp Zahn"
maintainer:          "20squares"
copyright:           "2022 20squares"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/manifold-hedger#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cassava
- open-games-hs
- path
- path-io
- probability
- vector


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  manifold-hedger-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - manifold-hedger

tests:
  manifold-hedger-test:
    main:                Spec.hs
    source-dirs:         src/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - manifold-hedger
    - hspec
